using BARD.Domain.Entities;
using BARD.Domain.Enums;

namespace BARD.Infrastructure.Persistence.Seed;

/// <summary>
/// Seed data for every localization key currently referenced by the
/// frontend (decision #2). Dutch (nl-BE) is the default language.
/// Idempotent: LocalizationSeeder only inserts keys that don't already
/// exist, so re-running seeding never overwrites administrator overrides.
/// </summary>
public static class LocalizationSeedData
{
    public static IEnumerable<LocalizationEntry> GetEntries()
    {
        yield return LocalizationEntry.Create("app.subtitle", TerminologyCategory.Other, "app", null, "Belgische Accijnzen Terugbetaling & Documentanalyse", "Analyseur belge de remboursement d'accises et de documents", "Belgischer Verbrauchsteuer-Rückerstattungs- und Dokumentenanalysator", "Belgian Accise Refund & Document Analyzer");
        yield return LocalizationEntry.Create("common.actions", TerminologyCategory.Other, "common", null, "Acties", "Actions", "Aktionen", "Actions");
        yield return LocalizationEntry.Create("common.cancel", TerminologyCategory.Other, "common", null, "Annuleren", "Annuler", "Abbrechen", "Cancel");
        yield return LocalizationEntry.Create("common.loading", TerminologyCategory.Other, "common", null, "Laden…", "Chargement…", "Wird geladen…", "Loading…");
        yield return LocalizationEntry.Create("common.save", TerminologyCategory.Other, "common", null, "Opslaan", "Enregistrer", "Speichern", "Save");
        yield return LocalizationEntry.Create("dossier.detail.approve_button", TerminologyCategory.ButtonCaption, "dossier", null, "Goedkeuren", "Approuver", "Genehmigen", "Approve");
        yield return LocalizationEntry.Create("dossier.detail.column_confidence", TerminologyCategory.ColumnHeading, "dossier", null, "Betrouwbaarheid", "Confiance", "Konfidenz", "Confidence");
        yield return LocalizationEntry.Create("dossier.detail.column_decision", TerminologyCategory.ColumnHeading, "dossier", null, "Beslissing", "Décision", "Entscheidung", "Decision");
        yield return LocalizationEntry.Create("dossier.detail.column_export", TerminologyCategory.ColumnHeading, "dossier", null, "Uitvoer", "Exportation", "Ausfuhr", "Export");
        yield return LocalizationEntry.Create("dossier.detail.column_invoice", TerminologyCategory.ColumnHeading, "dossier", null, "Factuurnr.", "N° facture", "Rechnungsnr.", "Invoice #");
        yield return LocalizationEntry.Create("dossier.detail.column_match", TerminologyCategory.ColumnHeading, "dossier", null, "Overeenkomst", "Correspondance", "Übereinstimmung", "Match");
        yield return LocalizationEntry.Create("dossier.detail.column_product", TerminologyCategory.ColumnHeading, "dossier", null, "Product", "Produit", "Produkt", "Product");
        yield return LocalizationEntry.Create("dossier.detail.column_refund", TerminologyCategory.ColumnHeading, "dossier", null, "Berekende teruggave", "Remboursement calculé", "Berechnete Erstattung", "Calculated refund");
        yield return LocalizationEntry.Create("dossier.detail.column_row", TerminologyCategory.ColumnHeading, "dossier", null, "Rij", "Ligne", "Zeile", "Row");
        yield return LocalizationEntry.Create("dossier.detail.export_button", TerminologyCategory.ButtonCaption, "dossier", null, "Rapport downloaden (Excel)", "Télécharger le rapport (Excel)", "Bericht herunterladen (Excel)", "Download report (Excel)");
        yield return LocalizationEntry.Create("dossier.detail.finding_country", TerminologyCategory.Other, "dossier", null, "Bestemming", "Destination", "Bestimmungsort", "Destination");
        yield return LocalizationEntry.Create("dossier.detail.finding_excise", TerminologyCategory.Other, "dossier", null, "Accijnscode", "Code d'accise", "Verbrauchsteuercode", "Excise code");
        yield return LocalizationEntry.Create("dossier.detail.finding_export_notes", TerminologyCategory.Other, "dossier", null, "Uitvoercontrole", "Contrôle d'exportation", "Ausfuhrprüfung", "Export check");
        yield return LocalizationEntry.Create("dossier.detail.finding_hard_block", TerminologyCategory.Other, "dossier", null, "Blokkering", "Blocage", "Sperre", "Hard block");
        yield return LocalizationEntry.Create("dossier.detail.finding_match_explanation", TerminologyCategory.Other, "dossier", null, "Toelichting overeenkomst", "Explication de la correspondance", "Erläuterung der Übereinstimmung", "Match explanation");
        yield return LocalizationEntry.Create("dossier.detail.finding_mrn", TerminologyCategory.Other, "dossier", null, "MRN", "MRN", "MRN", "MRN");
        yield return LocalizationEntry.Create("dossier.detail.finding_mrn_status", TerminologyCategory.Other, "dossier", null, "MRN/AC4-status", "Statut MRN/AC4", "MRN/AC4-Status", "MRN/AC4 status");
        yield return LocalizationEntry.Create("dossier.detail.finding_quantity", TerminologyCategory.Other, "dossier", null, "Hoeveelheid", "Quantité", "Menge", "Quantity");
        yield return LocalizationEntry.Create("dossier.detail.reject_button", TerminologyCategory.ButtonCaption, "dossier", null, "Afwijzen", "Rejeter", "Ablehnen", "Reject");
        yield return LocalizationEntry.Create("dossier.detail.remarks_label", TerminologyCategory.FieldLabel, "dossier", null, "Opmerkingen ambtenaar", "Remarques de l'agent", "Bemerkungen des Beamten", "Officer remarks");
        yield return LocalizationEntry.Create("dossier.detail.reviewed_by", TerminologyCategory.Other, "dossier", null, "Beoordeeld door {{name}} op {{date}}", "Vérifié par {{name}} le {{date}}", "Geprüft von {{name}} am {{date}}", "Reviewed by {{name}} on {{date}}");
        yield return LocalizationEntry.Create("dossier.list.column_application_date", TerminologyCategory.ColumnHeading, "dossier", null, "Aanvraagdatum", "Date de demande", "Antragsdatum", "Application date");
        yield return LocalizationEntry.Create("dossier.list.column_company", TerminologyCategory.ColumnHeading, "dossier", null, "Bedrijf", "Entreprise", "Unternehmen", "Company");
        yield return LocalizationEntry.Create("dossier.list.column_flagged", TerminologyCategory.ColumnHeading, "dossier", null, "Gemarkeerd", "Signalé", "Markiert", "Flagged");
        yield return LocalizationEntry.Create("dossier.list.column_lines", TerminologyCategory.ColumnHeading, "dossier", null, "Regels", "Lignes", "Zeilen", "Lines");
        yield return LocalizationEntry.Create("dossier.list.column_reference", TerminologyCategory.ColumnHeading, "dossier", null, "Referentie", "Référence", "Referenz", "Reference");
        yield return LocalizationEntry.Create("dossier.list.column_refund", TerminologyCategory.ColumnHeading, "dossier", null, "Berekende teruggave", "Remboursement calculé", "Berechnete Erstattung", "Calculated refund");
        yield return LocalizationEntry.Create("dossier.list.column_status", TerminologyCategory.ColumnHeading, "dossier", null, "Status", "Statut", "Status", "Status");
        yield return LocalizationEntry.Create("dossier.list.empty_state", TerminologyCategory.InformationalMessage, "dossier", null, "Nog geen dossiers. Klik op \"Nieuw dossier\" om er een te uploaden.", "Aucun dossier pour le moment. Cliquez sur « Nouveau dossier » pour en télécharger un.", "Noch keine Dossiers. Klicken Sie auf „Neues Dossier“, um eines hochzuladen.", "No dossiers yet. Click \"New dossier\" to upload one.");
        yield return LocalizationEntry.Create("dossier.list.new_button", TerminologyCategory.ButtonCaption, "dossier", null, "Nieuw dossier", "Nouveau dossier", "Neues Dossier", "New dossier");
        yield return LocalizationEntry.Create("dossier.list.title", TerminologyCategory.PageTitle, "dossier", null, "Dossiers", "Dossiers", "Dossiers", "Dossiers");
        yield return LocalizationEntry.Create("dossier.upload.excel_button", TerminologyCategory.ButtonCaption, "dossier", null, "Excel-claim van bedrijf uploaden", "Télécharger la déclaration Excel de l'entreprise", "Excel-Anspruch des Unternehmens hochladen", "Upload company Excel claim");
        yield return LocalizationEntry.Create("dossier.upload.field_address", TerminologyCategory.FieldLabel, "dossier", null, "Adres (optioneel)", "Adresse (facultatif)", "Adresse (optional)", "Address (optional)");
        yield return LocalizationEntry.Create("dossier.upload.field_application_date", TerminologyCategory.FieldLabel, "dossier", null, "Aanvraagdatum teruggave", "Date de demande de remboursement", "Antragsdatum der Erstattung", "Refund application date");
        yield return LocalizationEntry.Create("dossier.upload.field_city", TerminologyCategory.FieldLabel, "dossier", null, "Stad", "Ville", "Stadt", "City");
        yield return LocalizationEntry.Create("dossier.upload.field_company_name", TerminologyCategory.FieldLabel, "dossier", null, "Bedrijfsnaam", "Nom de l'entreprise", "Firmenname", "Company name");
        yield return LocalizationEntry.Create("dossier.upload.field_country", TerminologyCategory.FieldLabel, "dossier", null, "Land", "Pays", "Land", "Country");
        yield return LocalizationEntry.Create("dossier.upload.field_enterprise_number", TerminologyCategory.FieldLabel, "dossier", null, "Ondernemings-/btw-nummer", "Numéro d'entreprise/TVA", "Unternehmens-/USt-Nummer", "Enterprise / VAT number");
        yield return LocalizationEntry.Create("dossier.upload.field_postal_code", TerminologyCategory.FieldLabel, "dossier", null, "Postcode", "Code postal", "Postleitzahl", "Postal code");
        yield return LocalizationEntry.Create("dossier.upload.field_reference", TerminologyCategory.FieldLabel, "dossier", null, "Dossierreferentie", "Référence du dossier", "Dossierreferenz", "Dossier reference");
        yield return LocalizationEntry.Create("dossier.upload.pdfs_button", TerminologyCategory.ButtonCaption, "dossier", null, "Dossier-PDF's uploaden (facturen, AC4's, ...)", "Télécharger les PDF du dossier (factures, AC4, ...)", "Dossier-PDFs hochladen (Rechnungen, AC4, ...)", "Upload dossier PDFs (invoices, AC4s, ...)");
        yield return LocalizationEntry.Create("dossier.upload.result_summary", TerminologyCategory.InformationalMessage, "dossier", null, "{{rows}} rij(en), {{invoices}} factu(u)r(en), {{ac4}} AC4('s) verwerkt.", "{{rows}} ligne(s), {{invoices}} facture(s), {{ac4}} AC4 traité(s).", "{{rows}} Zeile(n), {{invoices}} Rechnung(en), {{ac4}} AC4 verarbeitet.", "Processed {{rows}} row(s), {{invoices}} invoice(s), {{ac4}} AC4(s).");
        yield return LocalizationEntry.Create("dossier.upload.section_company", TerminologyCategory.SectionTitle, "dossier", null, "Aanvragend bedrijf", "Entreprise demanderesse", "Antragstellendes Unternehmen", "Applicant company");
        yield return LocalizationEntry.Create("dossier.upload.section_documents", TerminologyCategory.SectionTitle, "dossier", null, "Documenten", "Documents", "Dokumente", "Documents");
        yield return LocalizationEntry.Create("dossier.upload.section_dossier", TerminologyCategory.SectionTitle, "dossier", null, "Dossier", "Dossier", "Dossier", "Dossier");
        yield return LocalizationEntry.Create("dossier.upload.submit_button", TerminologyCategory.ButtonCaption, "dossier", null, "Analyseren", "Analyser", "Analysieren", "Analyze");
        yield return LocalizationEntry.Create("dossier.upload.submit_error", TerminologyCategory.ValidationMessage, "dossier", null, "Verwerking mislukt. Controleer de bestanden en probeer opnieuw.", "Échec du traitement. Vérifiez les fichiers et réessayez.", "Verarbeitung fehlgeschlagen. Bitte Dateien prüfen und erneut versuchen.", "Processing failed. Please check the files and try again.");
        yield return LocalizationEntry.Create("dossier.upload.title", TerminologyCategory.PageTitle, "dossier", null, "Nieuw dossier — uploaden en analyseren", "Nouveau dossier — téléverser et analyser", "Neues Dossier — hochladen und analysieren", "New dossier — upload and analyze");
        yield return LocalizationEntry.Create("dossier.upload.unclassified_warning", TerminologyCategory.InformationalMessage, "dossier", null, "Kon niet classificeren:", "Impossible à classer :", "Konnte nicht klassifiziert werden:", "Could not classify:");
        yield return LocalizationEntry.Create("exciserates.admin.add_button", TerminologyCategory.ButtonCaption, "exciserates", null, "Accijnscode toevoegen", "Ajouter un code d'accise", "Verbrauchsteuercode hinzufügen", "Add excise code");
        yield return LocalizationEntry.Create("exciserates.admin.add_dialog_title", TerminologyCategory.Other, "exciserates", null, "Accijnscode toevoegen", "Ajouter un code d'accise", "Verbrauchsteuercode hinzufügen", "Add excise code");
        yield return LocalizationEntry.Create("exciserates.admin.column_active", TerminologyCategory.ColumnHeading, "exciserates", null, "Actief", "Actif", "Aktiv", "Active");
        yield return LocalizationEntry.Create("exciserates.admin.column_code", TerminologyCategory.ColumnHeading, "exciserates", null, "Code", "Code", "Code", "Code");
        yield return LocalizationEntry.Create("exciserates.admin.column_description", TerminologyCategory.ColumnHeading, "exciserates", null, "Omschrijving", "Description", "Beschreibung", "Description");
        yield return LocalizationEntry.Create("exciserates.admin.column_effective_from", TerminologyCategory.ColumnHeading, "exciserates", null, "Geldig vanaf", "Effectif à partir de", "Gültig ab", "Effective from");
        yield return LocalizationEntry.Create("exciserates.admin.column_rate", TerminologyCategory.ColumnHeading, "exciserates", null, "Tarief", "Taux", "Satz", "Rate");
        yield return LocalizationEntry.Create("exciserates.admin.column_status", TerminologyCategory.ColumnHeading, "exciserates", null, "Status", "Statut", "Status", "Status");
        yield return LocalizationEntry.Create("exciserates.admin.column_unit", TerminologyCategory.ColumnHeading, "exciserates", null, "Eenheid", "Unité", "Einheit", "Unit");
        yield return LocalizationEntry.Create("exciserates.admin.field_code", TerminologyCategory.FieldLabel, "exciserates", null, "Accijnscode", "Code d'accise", "Verbrauchsteuercode", "Excise code");
        yield return LocalizationEntry.Create("exciserates.admin.field_comment", TerminologyCategory.FieldLabel, "exciserates", null, "Administratieve opmerking (optioneel)", "Commentaire administratif (facultatif)", "Verwaltungshinweis (optional)", "Administrative comment (optional)");
        yield return LocalizationEntry.Create("exciserates.admin.field_description", TerminologyCategory.FieldLabel, "exciserates", null, "Omschrijving", "Description", "Beschreibung", "Description");
        yield return LocalizationEntry.Create("exciserates.admin.field_effective_from", TerminologyCategory.FieldLabel, "exciserates", null, "Geldig vanaf", "Effectif à partir de", "Gültig ab", "Effective from");
        yield return LocalizationEntry.Create("exciserates.admin.field_rate", TerminologyCategory.FieldLabel, "exciserates", null, "Tarief", "Taux", "Satz", "Rate");
        yield return LocalizationEntry.Create("exciserates.admin.field_unit", TerminologyCategory.FieldLabel, "exciserates", null, "Berekeningseenheid", "Unité de calcul", "Berechnungseinheit", "Calculation unit");
        yield return LocalizationEntry.Create("exciserates.admin.no_expiry_notice", TerminologyCategory.InformationalMessage, "exciserates", null, "Tarieven vervallen nooit automatisch en vereisen geen jaarlijkse herbevestiging. De organisatie is verantwoordelijk voor de wettelijke juistheid van de opgeslagen tarieven.", "Les taux n'expirent jamais automatiquement et ne nécessitent aucune reconfirmation annuelle. L'organisation est responsable de l'exactitude légale des taux enregistrés.", "Sätze laufen nie automatisch ab und erfordern keine jährliche Neubestätigung. Die Organisation ist für die rechtliche Richtigkeit der gespeicherten Sätze verantwortlich.", "Rates never expire automatically and require no annual reconfirmation. The organisation is responsible for the legal correctness of stored rates.");
        yield return LocalizationEntry.Create("exciserates.admin.status_active", TerminologyCategory.Other, "exciserates", null, "Actief", "Actif", "Aktiv", "Active");
        yield return LocalizationEntry.Create("exciserates.admin.status_inactive", TerminologyCategory.Other, "exciserates", null, "Inactief", "Inactif", "Inaktiv", "Inactive");
        yield return LocalizationEntry.Create("exciserates.admin.title", TerminologyCategory.PageTitle, "exciserates", null, "Instellingen > Accijnstarieven", "Paramètres > Taux d'accise", "Einstellungen > Verbrauchsteuersätze", "Settings > Excise Rates");
        yield return LocalizationEntry.Create("nav.dossiers", TerminologyCategory.NavigationLabel, "nav", null, "Dossiers", "Dossiers", "Dossiers", "Dossiers");
        yield return LocalizationEntry.Create("nav.edit_texts", TerminologyCategory.NavigationLabel, "nav", null, "Teksten bewerken", "Modifier les textes", "Texte bearbeiten", "Edit texts");
        yield return LocalizationEntry.Create("nav.excise_rates", TerminologyCategory.NavigationLabel, "nav", null, "Accijnstarieven", "Taux d'accise", "Verbrauchsteuersätze", "Excise Rates");
        yield return LocalizationEntry.Create("nav.terminology", TerminologyCategory.NavigationLabel, "nav", null, "Terminologie", "Terminologie", "Terminologie", "Terminology");
        yield return LocalizationEntry.Create("terminology.admin.column_key", TerminologyCategory.ColumnHeading, "terminology", null, "Sleutel", "Clé", "Schlüssel", "Key");
        yield return LocalizationEntry.Create("terminology.admin.column_module_screen", TerminologyCategory.ColumnHeading, "terminology", null, "Module / Scherm", "Module / Écran", "Modul / Bildschirm", "Module / Screen");
        yield return LocalizationEntry.Create("terminology.admin.missing", TerminologyCategory.Other, "terminology", null, "ontbrekend", "manquant", "fehlend", "missing");
        yield return LocalizationEntry.Create("terminology.admin.modified_chip", TerminologyCategory.Other, "terminology", null, "gewijzigd", "modifié", "geändert", "modified");
        yield return LocalizationEntry.Create("terminology.admin.only_missing_label", TerminologyCategory.FieldLabel, "terminology", null, "Alleen ontbrekende vertalingen", "Traductions manquantes uniquement", "Nur fehlende Übersetzungen", "Only missing translations");
        yield return LocalizationEntry.Create("terminology.admin.only_modified_label", TerminologyCategory.FieldLabel, "terminology", null, "Alleen door beheerder gewijzigd", "Modifié par l'administrateur uniquement", "Nur vom Administrator geändert", "Only administrator-modified");
        yield return LocalizationEntry.Create("terminology.admin.protected_chip", TerminologyCategory.Other, "terminology", null, "beschermd", "protégé", "geschützt", "protected");
        yield return LocalizationEntry.Create("terminology.admin.restore_all_tooltip", TerminologyCategory.Tooltip, "terminology", null, "Alle talen herstellen naar standaard", "Restaurer toutes les langues par défaut", "Alle Sprachen auf Standard zurücksetzen", "Restore all languages to default");
        yield return LocalizationEntry.Create("terminology.admin.restore_failed", TerminologyCategory.ValidationMessage, "terminology", null, "Standaardwaarde herstellen mislukt.", "Échec de la restauration de la valeur par défaut.", "Wiederherstellung des Standardwerts fehlgeschlagen.", "Failed to restore default value.");
        yield return LocalizationEntry.Create("terminology.admin.search_label", TerminologyCategory.FieldLabel, "terminology", null, "Zoeken", "Rechercher", "Suchen", "Search");
        yield return LocalizationEntry.Create("terminology.admin.title", TerminologyCategory.PageTitle, "terminology", null, "Instellingen > Terminologie", "Paramètres > Terminologie", "Einstellungen > Terminologie", "Settings > Terminology");
        yield return LocalizationEntry.Create("terminology.admin.view_history_tooltip", TerminologyCategory.Tooltip, "terminology", null, "Geschiedenis bekijken", "Voir l'historique", "Verlauf anzeigen", "View history");
        yield return LocalizationEntry.Create("terminology.editor.key_label", TerminologyCategory.FieldLabel, "terminology", null, "Lokalisatiesleutel", "Clé de localisation", "Lokalisierungsschlüssel", "Localization key");
        yield return LocalizationEntry.Create("terminology.editor.restore_default", TerminologyCategory.Other, "terminology", null, "Standaardwaarde herstellen", "Restaurer la valeur par défaut", "Standardwert wiederherstellen", "Restore default");
        yield return LocalizationEntry.Create("dossier.detail.export_error", TerminologyCategory.ValidationMessage, "dossier", null, "Kon het rapport niet genereren. Probeer het opnieuw.", "Impossible de générer le rapport. Veuillez réessayer.", "Der Bericht konnte nicht erstellt werden. Bitte versuchen Sie es erneut.", "Could not generate the report. Please try again.");
        yield return LocalizationEntry.Create("errors.not_found", TerminologyCategory.ValidationMessage, "errors", null, "Kon {entity} met sleutel '{key}' niet vinden.", "Impossible de trouver {entity} avec la clé « {key} ».", "{entity} mit Schlüssel „{key}“ konnte nicht gefunden werden.", "Could not find {entity} with key '{key}'.");
        yield return LocalizationEntry.Create("errors.forbidden", TerminologyCategory.ValidationMessage, "errors", null, "U hebt geen toestemming voor deze actie (vereist: {permission}).", "Vous n'êtes pas autorisé à effectuer cette action (requis : {permission}).", "Sie sind nicht berechtigt, diese Aktion auszuführen (erforderlich: {permission}).", "You are not permitted to perform this action (required: {permission}).");
        yield return LocalizationEntry.Create("errors.exciserate.cannot_delete_in_use", TerminologyCategory.ValidationMessage, "errors", null, "Accijnscode '{code}' is al gebruikt in een dossier en kan niet worden verwijderd. Deactiveer de code in plaats daarvan.", "Le code d'accise « {code} » a déjà été utilisé dans un dossier et ne peut pas être supprimé. Désactivez-le à la place.", "Der Verbrauchsteuercode „{code}“ wurde bereits in einem Dossier verwendet und kann nicht gelöscht werden. Deaktivieren Sie ihn stattdessen.", "Excise code '{code}' has already been used in a dossier and cannot be deleted. Deactivate it instead.");
        yield return LocalizationEntry.Create("errors.terminology.protected_key", TerminologyCategory.ValidationMessage, "errors", null, "Lokalisatiesleutel '{key}' is beschermd en kan niet inline worden bewerkt. Gebruik de centrale beheerpagina.", "La clé de localisation « {key} » est protégée et ne peut pas être modifiée en ligne. Utilisez la page d'administration centrale.", "Der Lokalisierungsschlüssel „{key}“ ist geschützt und kann nicht inline bearbeitet werden. Verwenden Sie die zentrale Verwaltungsseite.", "Localization key '{key}' is protected and cannot be changed via inline editing. Use central administration instead.");
        yield return LocalizationEntry.Create("errors.dossier.no_original_excel", TerminologyCategory.ValidationMessage, "errors", null, "Dossier '{reference}' heeft geen bewaard origineel Excel-claimdocument — exporteren niet mogelijk.", "Le dossier « {reference} » ne dispose d'aucun document Excel original conservé — exportation impossible.", "Dossier „{reference}“ hat kein gespeichertes Original-Excel-Dokument — Export nicht möglich.", "Dossier '{reference}' has no preserved original Excel claim document — cannot export.");
        yield return LocalizationEntry.Create("errors.dossier.export_row_mismatch", TerminologyCategory.ValidationMessage, "errors", null, "Dossier '{reference}': het originele werkblad lijkt te zijn gewijzigd na het uploaden — exporteren niet mogelijk.", "Dossier « {reference} » : la feuille de calcul d'origine semble avoir été modifiée après le téléchargement — exportation impossible.", "Dossier „{reference}“: Das Original-Arbeitsblatt scheint nach dem Hochladen geändert worden zu sein — Export nicht möglich.", "Dossier '{reference}': the original worksheet appears to have been modified after upload — cannot export.");
    }
}
